name: Check pods

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      report-file: report.log
    steps:
      - name: Connect to k3s host
        id: get-pods
        run: |
          mkdir ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          ssh-keyscan -H ${{ secrets.JUMP_IP }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_IP}} ssh-keyscan ${{ secrets.K3SHOST_IP }} >> ~/.ssh/known_hosts
          ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_IP }}" ${{ secrets.K3SHOST_USERNAME }}@${{ secrets.K3SHOST_IP }} "kubectl get pods -A" >> report

      - name: check-crashed-pods
        id: check-pods
        run: |
          echo "$(cat  report | grep -v Running)" >> ${{env.report-file}} 2>&1
          echo "pods-failed=$(cat report | grep -v Running | wc -l)" >> $GITHUB_OUTPUT

      - name: upload crashed pod's list
        if: steps.check_pods.outputs.pods-fail > 1
        uses: actions/upload-artifact@v3
        with:
          path: crash_report

      - name: slack Notification
        if: steps.check-pods.outputs.pods-fail > 1
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: notification_channel
          SLACK_COLOR: #FF0000
          SLACK_TITLE: 'Some pods have crashed'
          LACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Some pods have crashed'
          SLACK_USERNAME: GitHub Action
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
